// =============================================================
// Monaco 编辑器主题预设
// -------------------------------------------------------------
// 内置 vs / vs-dark 直接使用 Monaco 自带主题；
// 其余通过 defineTheme 注册，配色参考各流行编辑器主题。
// =============================================================

export const MONACO_THEME_STORAGE_KEY = "monaco-editor-theme";
export const DEFAULT_MONACO_THEME = "github-dark";

const NO_BORDER = "#00000000";

function editorColors({
  bg,
  fg,
  lineNum,
  lineNumActive,
  selection,
  lineHighlight,
  gutter,
  cursor,
}) {
  return {
    "editor.background": bg,
    "editor.foreground": fg,
    "editorLineNumber.foreground": lineNum,
    "editorLineNumber.activeForeground": lineNumActive ?? fg,
    "editor.selectionBackground": selection,
    "editor.lineHighlightBackground": lineHighlight,
    "editorGutter.background": gutter ?? bg,
    "editorCursor.foreground": cursor ?? fg,
    "focusBorder": NO_BORDER,
    "editor.lineHighlightBorder": NO_BORDER,
  };
}

/** @type {Array<{ id: string; name: string; kind: "light" | "dark"; swatch: string; builtin?: boolean; base?: string; colors?: Record<string, string>; rules?: Array<{ token: string; foreground?: string; fontStyle?: string }> }>} */
export const MONACO_THEMES = [
  {
    id: "vs",
    name: "Light 浅色",
    kind: "light",
    swatch: "#ffffff",
    builtin: true,
  },
  {
    id: "vs-dark",
    name: "Dark 暗色",
    kind: "dark",
    swatch: "#1e1e1e",
    builtin: true,
  },
  {
    id: "github-light",
    name: "GitHub Light",
    kind: "light",
    swatch: "#ffffff",
    base: "vs",
    colors: editorColors({
      bg: "#ffffff",
      fg: "#24292f",
      lineNum: "#8c959f",
      selection: "#b6e3ff",
      lineHighlight: "#f6f8fa",
      cursor: "#0969da",
    }),
    rules: [
      { token: "comment", foreground: "6e7781", fontStyle: "italic" },
      { token: "keyword", foreground: "cf222e" },
      { token: "string", foreground: "0a3069" },
      { token: "number", foreground: "0550ae" },
      { token: "type", foreground: "953800" },
      { token: "function", foreground: "8250df" },
    ],
  },
  {
    id: "github-dark",
    name: "GitHub Dark",
    kind: "dark",
    swatch: "#0d1117",
    base: "vs-dark",
    colors: editorColors({
      bg: "#0d1117",
      fg: "#c9d1d9",
      lineNum: "#6e7681",
      selection: "#264f78",
      lineHighlight: "#161b22",
      cursor: "#58a6ff",
    }),
    rules: [
      { token: "comment", foreground: "8b949e", fontStyle: "italic" },
      { token: "keyword", foreground: "ff7b72" },
      { token: "string", foreground: "a5d6ff" },
      { token: "number", foreground: "79c0ff" },
      { token: "type", foreground: "ffa657" },
      { token: "function", foreground: "d2a8ff" },
    ],
  },
  {
    id: "one-dark",
    name: "One Dark",
    kind: "dark",
    swatch: "#282c34",
    base: "vs-dark",
    colors: editorColors({
      bg: "#282c34",
      fg: "#abb2bf",
      lineNum: "#495162",
      selection: "#3e4451",
      lineHighlight: "#2c313a",
      cursor: "#528bff",
    }),
    rules: [
      { token: "comment", foreground: "5c6370", fontStyle: "italic" },
      { token: "keyword", foreground: "c678dd" },
      { token: "string", foreground: "98c379" },
      { token: "number", foreground: "d19a66" },
      { token: "type", foreground: "e5c07b" },
      { token: "function", foreground: "61afef" },
    ],
  },
  {
    id: "dracula",
    name: "Dracula",
    kind: "dark",
    swatch: "#282a36",
    base: "vs-dark",
    colors: editorColors({
      bg: "#282a36",
      fg: "#f8f8f2",
      lineNum: "#6272a4",
      selection: "#44475a",
      lineHighlight: "#313340",
      cursor: "#f8f8f0",
    }),
    rules: [
      { token: "comment", foreground: "6272a4", fontStyle: "italic" },
      { token: "keyword", foreground: "ff79c6" },
      { token: "string", foreground: "f1fa8c" },
      { token: "number", foreground: "bd93f9" },
      { token: "type", foreground: "8be9fd", fontStyle: "italic" },
      { token: "function", foreground: "50fa7b" },
    ],
  },
  {
    id: "monokai",
    name: "Monokai",
    kind: "dark",
    swatch: "#272822",
    base: "vs-dark",
    colors: editorColors({
      bg: "#272822",
      fg: "#f8f8f2",
      lineNum: "#90908a",
      selection: "#49483e",
      lineHighlight: "#3e3d32",
      cursor: "#f8f8f0",
    }),
    rules: [
      { token: "comment", foreground: "75715e", fontStyle: "italic" },
      { token: "keyword", foreground: "f92672" },
      { token: "string", foreground: "e6db74" },
      { token: "number", foreground: "ae81ff" },
      { token: "type", foreground: "66d9ef", fontStyle: "italic" },
      { token: "function", foreground: "a6e22e" },
    ],
  },
  {
    id: "solarized-light",
    name: "Solarized Light",
    kind: "light",
    swatch: "#fdf6e3",
    base: "vs",
    colors: editorColors({
      bg: "#fdf6e3",
      fg: "#657b83",
      lineNum: "#93a1a1",
      selection: "#eee8d5",
      lineHighlight: "#eee8d5",
      cursor: "#657b83",
    }),
    rules: [
      { token: "comment", foreground: "93a1a1", fontStyle: "italic" },
      { token: "keyword", foreground: "859900" },
      { token: "string", foreground: "2aa198" },
      { token: "number", foreground: "d33682" },
      { token: "type", foreground: "b58900" },
      { token: "function", foreground: "268bd2" },
    ],
  },
  {
    id: "solarized-dark",
    name: "Solarized Dark",
    kind: "dark",
    swatch: "#002b36",
    base: "vs-dark",
    colors: editorColors({
      bg: "#002b36",
      fg: "#839496",
      lineNum: "#586e75",
      selection: "#073642",
      lineHighlight: "#073642",
      cursor: "#839496",
    }),
    rules: [
      { token: "comment", foreground: "586e75", fontStyle: "italic" },
      { token: "keyword", foreground: "859900" },
      { token: "string", foreground: "2aa198" },
      { token: "number", foreground: "d33682" },
      { token: "type", foreground: "b58900" },
      { token: "function", foreground: "268bd2" },
    ],
  },
  {
    id: "nord",
    name: "Nord",
    kind: "dark",
    swatch: "#2e3440",
    base: "vs-dark",
    colors: editorColors({
      bg: "#2e3440",
      fg: "#d8dee9",
      lineNum: "#4c566a",
      selection: "#434c5e",
      lineHighlight: "#3b4252",
      cursor: "#d8dee9",
    }),
    rules: [
      { token: "comment", foreground: "616e88", fontStyle: "italic" },
      { token: "keyword", foreground: "81a1c1" },
      { token: "string", foreground: "a3be8c" },
      { token: "number", foreground: "b48ead" },
      { token: "type", foreground: "8fbcbb" },
      { token: "function", foreground: "88c0d0" },
    ],
  },
  // ===== Material Theme 系列（VS Code 最热门主题之一） =====
  {
    id: "material-theme-darker",
    name: "Material Theme Darker",
    kind: "dark",
    swatch: "#212121",
    base: "vs-dark",
    colors: editorColors({
      bg: "#212121",
      fg: "#eeffff",
      lineNum: "#4a4a4a",
      selection: "#2c2c2c",
      lineHighlight: "#2a2a2a",
      cursor: "#ffcc00",
    }),
    rules: [
      { token: "comment", foreground: "545454", fontStyle: "italic" },
      { token: "keyword", foreground: "c792ea" },
      { token: "string", foreground: "c3e88d" },
      { token: "number", foreground: "f78c6c" },
      { token: "type", foreground: "ffcb6b" },
      { token: "function", foreground: "82aaff" },
    ],
  },
  {
    id: "material-theme-palenight",
    name: "Material Palenight",
    kind: "dark",
    swatch: "#292d3e",
    base: "vs-dark",
    colors: editorColors({
      bg: "#292d3e",
      fg: "#a6accd",
      lineNum: "#3a3f58",
      selection: "#3c435e",
      lineHighlight: "#2c3050",
      cursor: "#ffcc00",
    }),
    rules: [
      { token: "comment", foreground: "676e95", fontStyle: "italic" },
      { token: "keyword", foreground: "c792ea" },
      { token: "string", foreground: "c3e88d" },
      { token: "number", foreground: "f78c6c" },
      { token: "type", foreground: "ffcb6b" },
      { token: "function", foreground: "82aaff" },
    ],
  },
  // ===== Tokyo Night 系列（近年在 VS Code 热门榜上升） =====
  {
    id: "tokyo-night",
    name: "Tokyo Night",
    kind: "dark",
    swatch: "#1a1b26",
    base: "vs-dark",
    colors: editorColors({
      bg: "#1a1b26",
      fg: "#a9b1d6",
      lineNum: "#3b4261",
      selection: "#33467c",
      lineHighlight: "#16161e",
      cursor: "#c0caf5",
    }),
    rules: [
      { token: "comment", foreground: "565f89", fontStyle: "italic" },
      { token: "keyword", foreground: "bb9af7" },
      { token: "string", foreground: "9ece6a" },
      { token: "number", foreground: "ff9e64" },
      { token: "type", foreground: "2ac3de" },
      { token: "function", foreground: "7aa2f7" },
    ],
  },
  {
    id: "tokyo-night-storm",
    name: "Tokyo Night Storm",
    kind: "dark",
    swatch: "#24283b",
    base: "vs-dark",
    colors: editorColors({
      bg: "#24283b",
      fg: "#a9b1d6",
      lineNum: "#3d4261",
      selection: "#2e3c64",
      lineHighlight: "#1f2335",
      cursor: "#c0caf5",
    }),
    rules: [
      { token: "comment", foreground: "565f89", fontStyle: "italic" },
      { token: "keyword", foreground: "bb9af7" },
      { token: "string", foreground: "9ece6a" },
      { token: "number", foreground: "ff9e64" },
      { token: "type", foreground: "2ac3de" },
      { token: "function", foreground: "7aa2f7" },
    ],
  },
  // ===== Catppuccin 系列（VS Code 近年最热门配色） =====
  {
    id: "catppuccin-mocha",
    name: "Catppuccin Mocha",
    kind: "dark",
    swatch: "#1e1e2e",
    base: "vs-dark",
    colors: editorColors({
      bg: "#1e1e2e",
      fg: "#cdd6f4",
      lineNum: "#45475a",
      selection: "#585b70",
      lineHighlight: "#181825",
      cursor: "#f5e0dc",
    }),
    rules: [
      { token: "comment", foreground: "6c7086", fontStyle: "italic" },
      { token: "keyword", foreground: "cba6f7" },
      { token: "string", foreground: "a6e3a1" },
      { token: "number", foreground: "fab387" },
      { token: "type", foreground: "f9e2af" },
      { token: "function", foreground: "89b4fa" },
    ],
  },
  {
    id: "catppuccin-latte",
    name: "Catppuccin Latte",
    kind: "light",
    swatch: "#eff1f5",
    base: "vs",
    colors: editorColors({
      bg: "#eff1f5",
      fg: "#4c4f69",
      lineNum: "#9ca0b0",
      selection: "#bcc0cc",
      lineHighlight: "#e6e9ef",
      cursor: "#dc8a78",
    }),
    rules: [
      { token: "comment", foreground: "7287fd", fontStyle: "italic" },
      { token: "keyword", foreground: "8839ef" },
      { token: "string", foreground: "40a02b" },
      { token: "number", foreground: "fe640b" },
      { token: "type", foreground: "df8e1d" },
      { token: "function", foreground: "1e66f5" },
    ],
  },
  // ===== Ayu 系列 =====
  {
    id: "ayu-mirage",
    name: "Ayu Mirage",
    kind: "dark",
    swatch: "#1f2430",
    base: "vs-dark",
    colors: editorColors({
      bg: "#1f2430",
      fg: "#cbccc6",
      lineNum: "#323847",
      selection: "#2d3543",
      lineHighlight: "#191e2a",
      cursor: "#ffcc66",
    }),
    rules: [
      { token: "comment", foreground: "5c6773", fontStyle: "italic" },
      { token: "keyword", foreground: "ffa759" },
      { token: "string", foreground: "bae67e" },
      { token: "number", foreground: "ffcc66" },
      { token: "type", foreground: "5ccfe6" },
      { token: "function", foreground: "ffd580" },
    ],
  },
  // ===== Synthwave '84（霓虹复古风，热门） =====
  {
    id: "synthwave-84",
    name: "Synthwave '84",
    kind: "dark",
    swatch: "#262335",
    base: "vs-dark",
    colors: editorColors({
      bg: "#262335",
      fg: "#ffffff",
      lineNum: "#495495",
      selection: "#463465",
      lineHighlight: "#2a2440",
      cursor: "#f92aad",
    }),
    rules: [
      { token: "comment", foreground: "848bbd", fontStyle: "italic" },
      { token: "keyword", foreground: "f92aad" },
      { token: "string", foreground: "f97e72" },
      { token: "number", foreground: "ff8b39" },
      { token: "type", foreground: "36f9f6" },
      { token: "function", foreground: "fe4450" },
    ],
  },
  // ===== Gruvbox 系列（复古暖色调，极受欢迎） =====
  {
    id: "gruvbox-dark",
    name: "Gruvbox Dark",
    kind: "dark",
    swatch: "#282828",
    base: "vs-dark",
    colors: editorColors({
      bg: "#282828",
      fg: "#ebdbb2",
      lineNum: "#7c6f64",
      selection: "#504945",
      lineHighlight: "#3c3836",
      cursor: "#ebdbb2",
    }),
    rules: [
      { token: "comment", foreground: "928374", fontStyle: "italic" },
      { token: "keyword", foreground: "fb4934" },
      { token: "string", foreground: "b8bb26" },
      { token: "number", foreground: "d3869b" },
      { token: "type", foreground: "fabd2f" },
      { token: "function", foreground: "8ec07c" },
    ],
  },
  {
    id: "gruvbox-light",
    name: "Gruvbox Light",
    kind: "light",
    swatch: "#fbf1c7",
    base: "vs",
    colors: editorColors({
      bg: "#fbf1c7",
      fg: "#3c3836",
      lineNum: "#928374",
      selection: "#d5c4a1",
      lineHighlight: "#ebdbb2",
      cursor: "#3c3836",
    }),
    rules: [
      { token: "comment", foreground: "928374", fontStyle: "italic" },
      { token: "keyword", foreground: "9d0006" },
      { token: "string", foreground: "79740e" },
      { token: "number", foreground: "8f3f71" },
      { token: "type", foreground: "b57614" },
      { token: "function", foreground: "427b58" },
    ],
  },
  // ===== Night Owl / Light Owl（Sarah Drasner 出品，热门） =====
  {
    id: "night-owl",
    name: "Night Owl",
    kind: "dark",
    swatch: "#011627",
    base: "vs-dark",
    colors: editorColors({
      bg: "#011627",
      fg: "#d6deeb",
      lineNum: "#4b6479",
      selection: "#1d3b53",
      lineHighlight: "#023047",
      cursor: "#80a4c2",
    }),
    rules: [
      { token: "comment", foreground: "637777", fontStyle: "italic" },
      { token: "keyword", foreground: "c792ea" },
      { token: "string", foreground: "ecc48d" },
      { token: "number", foreground: "f78c6c" },
      { token: "type", foreground: "82aaff" },
      { token: "function", foreground: "82aaff" },
    ],
  },
  {
    id: "light-owl",
    name: "Light Owl",
    kind: "light",
    swatch: "#fbfbfb",
    base: "vs",
    colors: editorColors({
      bg: "#fbfbfb",
      fg: "#404b54",
      lineNum: "#90a4a4",
      selection: "#e0e0e0",
      lineHighlight: "#f0f0f0",
      cursor: "#404b54",
    }),
    rules: [
      { token: "comment", foreground: "90a4a4", fontStyle: "italic" },
      { token: "keyword", foreground: "aa567c" },
      { token: "string", foreground: "b6744a" },
      { token: "number", foreground: "0c969b" },
      { token: "type", foreground: "2f6f9f" },
      { token: "function", foreground: "2f6f9f" },
    ],
  },
  // ===== Cobalt2（Wes Bos 出品，热门） =====
  {
    id: "cobalt2",
    name: "Cobalt2",
    kind: "dark",
    swatch: "#193549",
    base: "vs-dark",
    colors: editorColors({
      bg: "#193549",
      fg: "#ffffff",
      lineNum: "#3c5a78",
      selection: "#1f4262",
      lineHighlight: "#15232d",
      cursor: "#ffc600",
    }),
    rules: [
      { token: "comment", foreground: "0088ff", fontStyle: "italic" },
      { token: "keyword", foreground: "ffc600" },
      { token: "string", foreground: "a5ff90" },
      { token: "number", foreground: "ff628c" },
      { token: "type", foreground: "ff9d00" },
      { token: "function", foreground: "80d4ff" },
    ],
  },
  // ===== One Monokai（One Dark 与 Monokai 融合） =====
  {
    id: "one-monokai",
    name: "One Monokai",
    kind: "dark",
    swatch: "#282c34",
    base: "vs-dark",
    colors: editorColors({
      bg: "#282c34",
      fg: "#abb2bf",
      lineNum: "#4b525d",
      selection: "#3e4451",
      lineHighlight: "#2c313a",
      cursor: "#528bff",
    }),
    rules: [
      { token: "comment", foreground: "5c6370", fontStyle: "italic" },
      { token: "keyword", foreground: "c678dd" },
      { token: "string", foreground: "98c379" },
      { token: "number", foreground: "d19a66" },
      { token: "type", foreground: "61afef" },
      { token: "function", foreground: "61afef" },
    ],
  },
  // ===== Kanagawa（日式水墨配色，近期 VS Code 极受欢迎） =====
  {
    id: "kanagawa",
    name: "Kanagawa",
    kind: "dark",
    swatch: "#1f1f28",
    base: "vs-dark",
    colors: editorColors({
      bg: "#1f1f28",
      fg: "#dcd7ba",
      lineNum: "#2a2a37",
      selection: "#2d4f67",
      lineHighlight: "#16161d",
      cursor: "#c8c093",
    }),
    rules: [
      { token: "comment", foreground: "727169", fontStyle: "italic" },
      { token: "keyword", foreground: "957fb8" },
      { token: "string", foreground: "98bb6c" },
      { token: "number", foreground: "d27e99" },
      { token: "type", foreground: "7aa89f" },
      { token: "function", foreground: "7e9cd8" },
    ],
  },
  // ===== Rosé Pine 系列（柔和暗色，近期热门） =====
  {
    id: "rose-pine",
    name: "Rosé Pine",
    kind: "dark",
    swatch: "#191724",
    base: "vs-dark",
    colors: editorColors({
      bg: "#191724",
      fg: "#e0def4",
      lineNum: "#403d52",
      selection: "#26233a",
      lineHighlight: "#1f1d2e",
      cursor: "#e0def4",
    }),
    rules: [
      { token: "comment", foreground: "6e6a86", fontStyle: "italic" },
      { token: "keyword", foreground: "31748f" },
      { token: "string", foreground: "ebbcba" },
      { token: "number", foreground: "ebbcba" },
      { token: "type", foreground: "9ccfd8" },
      { token: "function", foreground: "ebbcba" },
    ],
  },
  {
    id: "rose-pine-moon",
    name: "Rosé Pine Moon",
    kind: "dark",
    swatch: "#232136",
    base: "vs-dark",
    colors: editorColors({
      bg: "#232136",
      fg: "#e0def4",
      lineNum: "#393552",
      selection: "#312c46",
      lineHighlight: "#2a273f",
      cursor: "#e0def4",
    }),
    rules: [
      { token: "comment", foreground: "6e6a86", fontStyle: "italic" },
      { token: "keyword", foreground: "3e8fb0" },
      { token: "string", foreground: "ea9a97" },
      { token: "number", foreground: "ea9a97" },
      { token: "type", foreground: "9ccfd8" },
      { token: "function", foreground: "ea9a97" },
    ],
  },
  // ===== Everforest（森系暗色，护眼热门） =====
  {
    id: "everforest-dark",
    name: "Everforest Dark",
    kind: "dark",
    swatch: "#2b3339",
    base: "vs-dark",
    colors: editorColors({
      bg: "#2b3339",
      fg: "#d3c6aa",
      lineNum: "#414b50",
      selection: "#3a453a",
      lineHighlight: "#272d32",
      cursor: "#d3c6aa",
    }),
    rules: [
      { token: "comment", foreground: "7a8478", fontStyle: "italic" },
      { token: "keyword", foreground: "a7c080" },
      { token: "string", foreground: "dbbc7f" },
      { token: "number", foreground: "e67e80" },
      { token: "type", foreground: "83c092" },
      { token: "function", foreground: "7fbbb3" },
    ],
  },
  // ===== Andromeda（多彩深空配色，热门） =====
  {
    id: "andromeda",
    name: "Andromeda",
    kind: "dark",
    swatch: "#23262e",
    base: "vs-dark",
    colors: editorColors({
      bg: "#23262e",
      fg: "#e6e6e6",
      lineNum: "#454852",
      selection: "#3c3f4a",
      lineHighlight: "#2c2f36",
      cursor: "#ffb86c",
    }),
    rules: [
      { token: "comment", foreground: "787890", fontStyle: "italic" },
      { token: "keyword", foreground: "c678dd" },
      { token: "string", foreground: "97c3f6" },
      { token: "number", foreground: "ffb86c" },
      { token: "type", foreground: "56b6c2" },
      { token: "function", foreground: "82aaff" },
    ],
  },
  // ===== Shades of Purple（高对比紫色调，热门） =====
  {
    id: "shades-of-purple",
    name: "Shades of Purple",
    kind: "dark",
    swatch: "#1e1e3f",
    base: "vs-dark",
    colors: editorColors({
      bg: "#1e1e3f",
      fg: "#ffffff",
      lineNum: "#4d4d7a",
      selection: "#3a3a5e",
      lineHighlight: "#2a2a4a",
      cursor: "#fad000",
    }),
    rules: [
      { token: "comment", foreground: "7c7c9e", fontStyle: "italic" },
      { token: "keyword", foreground: "ff628c" },
      { token: "string", foreground: "a5ff90" },
      { token: "number", foreground: "fad000" },
      { token: "type", foreground: "9effff" },
      { token: "function", foreground: "fb94ff" },
    ],
  },
  // ===== Dark Modern（VS Code 1.80+ 默认暗色） =====
  {
    id: "dark-modern",
    name: "Dark Modern",
    kind: "dark",
    swatch: "#1f1f1f",
    base: "vs-dark",
    colors: editorColors({
      bg: "#1f1f1f",
      fg: "#cccccc",
      lineNum: "#6e7681",
      selection: "#264f78",
      lineHighlight: "#2a2d2e",
      cursor: "#aeafad",
    }),
    rules: [
      { token: "comment", foreground: "6a9955", fontStyle: "italic" },
      { token: "keyword", foreground: "569cd6" },
      { token: "string", foreground: "ce9178" },
      { token: "number", foreground: "b5cea8" },
      { token: "type", foreground: "4ec9b0" },
      { token: "function", foreground: "dcdcaa" },
    ],
  },
  // ===== Dark+（VS Code 经典默认暗色） =====
  {
    id: "dark-plus",
    name: "Dark+",
    kind: "dark",
    swatch: "#1e1e1e",
    base: "vs-dark",
    colors: editorColors({
      bg: "#1e1e1e",
      fg: "#d4d4d4",
      lineNum: "#858585",
      selection: "#264f78",
      lineHighlight: "#2a2d2e",
      cursor: "#aeafad",
    }),
    rules: [
      { token: "comment", foreground: "6a9955", fontStyle: "italic" },
      { token: "keyword", foreground: "569cd6" },
      { token: "string", foreground: "ce9178" },
      { token: "number", foreground: "b5cea8" },
      { token: "type", foreground: "4ec9b0" },
      { token: "function", foreground: "dcdcaa" },
    ],
  },
  // ===== Midnight Synth（深夜合成器风，霓虹感） =====
  {
    id: "midnight-synth",
    name: "Midnight Synth",
    kind: "dark",
    swatch: "#0a1929",
    base: "vs-dark",
    colors: editorColors({
      bg: "#0a1929",
      fg: "#c5e4fd",
      lineNum: "#1a3a52",
      selection: "#1d3b53",
      lineHighlight: "#0d2137",
      cursor: "#7e57c2",
    }),
    rules: [
      { token: "comment", foreground: "4a6a8a", fontStyle: "italic" },
      { token: "keyword", foreground: "c792ea" },
      { token: "string", foreground: "c3e88d" },
      { token: "number", foreground: "f78c6c" },
      { token: "type", foreground: "82aaff" },
      { token: "function", foreground: "82aaff" },
    ],
  },
  // ===== Future Funk（复古未来主义霓虹风） =====
  {
    id: "future-funk",
    name: "Future Funk",
    kind: "dark",
    swatch: "#1a1a2e",
    base: "vs-dark",
    colors: editorColors({
      bg: "#1a1a2e",
      fg: "#e0e0e0",
      lineNum: "#3a3a52",
      selection: "#2a2a4e",
      lineHighlight: "#16162a",
      cursor: "#ff6ac1",
    }),
    rules: [
      { token: "comment", foreground: "5c5c7a", fontStyle: "italic" },
      { token: "keyword", foreground: "ff6ac1" },
      { token: "string", foreground: "54e3ff" },
      { token: "number", foreground: "ffd700" },
      { token: "type", foreground: "54e3ff" },
      { token: "function", foreground: "50fa7b" },
    ],
  },
  // ===== Forest Night（森林夜色调，护眼） =====
  {
    id: "forest-night",
    name: "Forest Night",
    kind: "dark",
    swatch: "#1c1e20",
    base: "vs-dark",
    colors: editorColors({
      bg: "#1c1e20",
      fg: "#c0c8cf",
      lineNum: "#3a4045",
      selection: "#2d3438",
      lineHighlight: "#1a1c1e",
      cursor: "#9bb86b",
    }),
    rules: [
      { token: "comment", foreground: "5a6268", fontStyle: "italic" },
      { token: "keyword", foreground: "9bb86b" },
      { token: "string", foreground: "e5c07b" },
      { token: "number", foreground: "d19a66" },
      { token: "type", foreground: "83b3c0" },
      { token: "function", foreground: "83b3c0" },
    ],
  },
  // ===== Outer Wilds（深空暗色调，神秘风） =====
  {
    id: "outer-wilds",
    name: "Outer Wilds",
    kind: "dark",
    swatch: "#0d0e16",
    base: "vs-dark",
    colors: editorColors({
      bg: "#0d0e16",
      fg: "#e0e0e0",
      lineNum: "#2a2b3d",
      selection: "#1e1f30",
      lineHighlight: "#101120",
      cursor: "#ffb347",
    }),
    rules: [
      { token: "comment", foreground: "4a4b5e", fontStyle: "italic" },
      { token: "keyword", foreground: "#ff7f50" },
      { token: "string", foreground: "#ffd700" },
      { token: "number", foreground: "#87ceeb" },
      { token: "type", foreground: "#ff69b4" },
      { token: "function", foreground: "#ff69b4" },
    ],
  },
];

export function getMonacoTheme(id) {
  return MONACO_THEMES.find((t) => t.id === id) ?? MONACO_THEMES[0];
}

let registered = false;

/** 注册所有自定义 Monaco 主题（幂等，全局只执行一次） */
export function registerMonacoThemes(monaco) {
  if (registered) return;
  registered = true;

  for (const theme of MONACO_THEMES) {
    if (theme.builtin) continue;
    monaco.editor.defineTheme(theme.id, {
      base: theme.base,
      inherit: true,
      rules: theme.rules ?? [],
      colors: theme.colors ?? {},
    });
  }
}
